# STAGING: 1 replica, updated automatically on every merge to master.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-gitops
  namespace: demo-staging
  labels:
    app: node-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-gitops
  template:
    metadata:
      labels:
        app: node-gitops
    spec:
      containers:
        - name: node-gitops
          image: ghcr.io/arasrasouli/node-gitops-app:6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
