apiVersion: v1
kind: Service
metadata:
  name: node-gitops-service
  namespace: demo-production
spec:
  selector:
    app: node-gitops
  ports:
    - port: 8090
      targetPort: 3000
  type: LoadBalancer
